### ISSUE TITLE
Regex compile error

### ISSUE THREAD

**Issue by grantramsay** [sualeh/pointlocation6709#2]
Hi, I get a regex compile error:

    java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 19
    (\d+\.?\d*)[°'"]\b*
    ...
    at us.fatehi.pointlocation6709.parse.CoordinateParser.<init>(CoordinateParser.java:79)
For this line:

    private final Pattern patternAngleFields = Pattern.compile("(\\d+\\.?\\d*)[\u00B0\'\"]\\b*");

https://regex101.com/ doesn't like the `*` quantifier where it is:
<img width="701" alt="Screen Shot 2019-09-19 at 2 13 49 PM" src="https://user-images.githubusercontent.com/8636545/65243074-e6715b80-dae7-11e9-95ad-c4a39ac2b784.png">

**Comment by sualeh** [comment]
Updated all files to UTF-8.
